# Generated by Django 3.0 on 2019-12-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('music_id', models.AutoField(primary_key=True, serialize=False)),
                ('music_name', models.CharField(max_length=50)),
                ('music_singer', models.CharField(max_length=50)),
                ('music_duration', models.FloatField()),
                ('like', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('playlist_name', models.CharField(max_length=50)),
                ('musics', models.ManyToManyField(to='musicly.Music')),
            ],
        ),
    ]
