# Generated by Django 3.0 on 2019-12-04 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicly', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='music_duration',
        ),
    ]
